version: '3'
services:
  web:
    image: aronpc/cati-php:latest-nginx
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - mailhog
    ports:
        - "8085:8080"
    # labels:
    #  - 'traefik.frontend.rule=Host:$APP_NAME.teste'

  mysql:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_DATABASE
      volumes:
          - mysql:/data/mysql
      labels:
          - 'traefik.enable=false'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.frontend.rule=Host:mail.teste'
      - 'traefik.port=1025'

  adminer:
    image: adminer
    labels:
      - 'traefik.frontend.rule=Host:adminer.teste'

networks:
  default:
    external:
      name: web

volumes:
  mysql:

